// ═══════════════════════════════════════════════════════════════
//  The Testimony — prophecies of the Messiah, written centuries
//  before His birth, and their fulfillment in Jesus Christ.
//  The convergence of all convergences.
//
//  "And beginning with Moses and all the Prophets, He interpreted
//   to them in all the Scriptures the things concerning Himself."
//   — Luke 24:27
// ═══════════════════════════════════════════════════════════════

import type { Prophecy } from "../types";
import { Oracle } from "./rng";

export const PROPHECIES: Prophecy[] = [
  {
    id: "seed",
    theme: "lineage",
    prophecyRef: "Genesis 3:15",
    prophecyText: "I will put enmity between you and the woman, and between your offspring and hers; He will crush your head, and you will strike His heel.",
    fulfillmentRef: "Galatians 4:4; 1 John 3:8",
    fulfillmentText: "When the fullness of time had come, God sent forth His Son, born of a woman — to destroy the works of the devil.",
    written: "the first promise",
    insight: "The very first page of Scripture holds a wound and a rescue: the heel struck at the Cross, the serpent's head crushed by Resurrection. Hope was planted before the gate of Eden closed.",
  },
  {
    id: "abraham",
    theme: "lineage",
    prophecyRef: "Genesis 22:18",
    prophecyText: "Through your offspring all nations on earth will be blessed, because you have obeyed Me.",
    fulfillmentRef: "Matthew 1:1; Galatians 3:16",
    fulfillmentText: "The genealogy of Jesus Christ, the son of David, the son of Abraham. The promises were spoken to Abraham and to his Seed — who is Christ.",
    written: "c. 2000 BC",
    insight: "A blessing meant for every nation, narrowed to a single family line, then opened again to the whole world in one Man. The funnel of history pointing to Bethlehem.",
  },
  {
    id: "judah",
    theme: "lineage",
    prophecyRef: "Genesis 49:10",
    prophecyText: "The scepter will not depart from Judah, nor the ruler's staff from between his feet, until He to whom it belongs shall come, and the obedience of the nations shall be His.",
    fulfillmentRef: "Hebrews 7:14; Revelation 5:5",
    fulfillmentText: "It is clear that our Lord descended from Judah. Behold, the Lion of the tribe of Judah has triumphed.",
    written: "c. 1700 BC",
    insight: "Centuries before there was a king in Israel, the royal tribe was named. The Lion would come from Judah — and He came.",
  },
  {
    id: "david",
    theme: "kingship",
    prophecyRef: "2 Samuel 7:12-13; Jeremiah 23:5",
    prophecyText: "I will raise up your offspring after you, and I will establish his kingdom forever. A righteous Branch from David who will reign as King.",
    fulfillmentRef: "Luke 1:32-33",
    fulfillmentText: "He will be great, and the Lord God will give Him the throne of His father David, and He will reign forever; His kingdom will never end.",
    written: "c. 1000 BC",
    insight: "An everlasting throne promised to a shepherd-king who would himself die. Only an eternal Son could fulfill a forever kingdom.",
  },
  {
    id: "virgin",
    theme: "birth",
    prophecyRef: "Isaiah 7:14",
    prophecyText: "Therefore the Lord himself will give you a sign: the virgin will conceive and give birth to a son, and will call him Immanuel — God with us.",
    fulfillmentRef: "Matthew 1:22-23",
    fulfillmentText: "All this took place to fulfill what the Lord had said: 'The virgin will conceive and give birth to a son, and they will call Him Immanuel.'",
    written: "c. 700 BC",
    insight: "The sign was not merely a birth, but a Name: God with us. The infinite God consenting to be carried, nursed, and held.",
  },
  {
    id: "bethlehem",
    theme: "birth",
    prophecyRef: "Micah 5:2",
    prophecyText: "But you, Bethlehem Ephrathah, though you are small among the clans of Judah, out of you will come for Me one who will be ruler over Israel, whose origins are from of old, from ancient times.",
    fulfillmentRef: "Matthew 2:1; Luke 2:4-7",
    fulfillmentText: "After Jesus was born in Bethlehem in Judea, during the time of King Herod...",
    written: "c. 700 BC",
    insight: "The town is named seven centuries early — and the prophet quietly says His 'origins are from ancient times.' The Child of Bethlehem is older than the stars.",
  },
  {
    id: "egypt",
    theme: "birth",
    prophecyRef: "Hosea 11:1",
    prophecyText: "When Israel was a child, I loved him, and out of Egypt I called my son.",
    fulfillmentRef: "Matthew 2:14-15",
    fulfillmentText: "So he got up, took the child and his mother and escaped to Egypt, where he stayed until the death of Herod — to fulfill what the Lord had said.",
    written: "c. 750 BC",
    insight: "Christ relives Israel's whole story — the exile, the exodus — and gets it right where the nation failed. He is the true and faithful Son.",
  },
  {
    id: "forerunner",
    theme: "ministry",
    prophecyRef: "Isaiah 40:3; Malachi 3:1",
    prophecyText: "A voice of one calling: in the wilderness prepare the way for the Lord. I will send my messenger, who will prepare the way before me.",
    fulfillmentRef: "Matthew 3:1-3; Mark 1:2-4",
    fulfillmentText: "In those days John the Baptist came, preaching in the wilderness of Judea: 'Prepare the way for the Lord.'",
    written: "c. 700-430 BC",
    insight: "Even the herald was foretold. Grace announces itself before it arrives, that no one would be caught unprepared by mercy.",
  },
  {
    id: "galilee",
    theme: "ministry",
    prophecyRef: "Isaiah 9:1-2",
    prophecyText: "In the future He will honor Galilee of the nations. The people walking in darkness have seen a great light.",
    fulfillmentRef: "Matthew 4:13-16",
    fulfillmentText: "Leaving Nazareth, He went and lived in Capernaum... to fulfill what was said: 'The people living in darkness have seen a great light.'",
    written: "c. 700 BC",
    insight: "Not to the temple courts first, but to the forgotten northern roads. The Light goes where the darkness is thickest.",
  },
  {
    id: "anointed",
    theme: "ministry",
    prophecyRef: "Isaiah 61:1-2",
    prophecyText: "The Spirit of the Sovereign Lord is on me, because the Lord has anointed me to proclaim good news to the poor, to bind up the brokenhearted, to proclaim freedom for the captives.",
    fulfillmentRef: "Luke 4:17-21",
    fulfillmentText: "He found the place where it is written... and He began by saying, 'Today this Scripture is fulfilled in your hearing.'",
    written: "c. 700 BC",
    insight: "He read His own job description aloud, then closed the scroll and said: today. The waiting of centuries collapsed into a single morning.",
  },
  {
    id: "parables",
    theme: "ministry",
    prophecyRef: "Psalm 78:2",
    prophecyText: "I will open my mouth in parables, I will utter hidden things, things from of old.",
    fulfillmentRef: "Matthew 13:34-35",
    fulfillmentText: "Jesus spoke all these things to the crowd in parables; He did not say anything to them without using a parable.",
    written: "c. 1000 BC",
    insight: "The deepest truths came wrapped in seeds, coins, and lost sheep — hidden in plain sight, found only by the hungry heart.",
  },
  {
    id: "triumphal",
    theme: "passion",
    prophecyRef: "Zechariah 9:9",
    prophecyText: "Rejoice greatly, Daughter Zion! See, your king comes to you, righteous and victorious, lowly and riding on a donkey, on a colt, the foal of a donkey.",
    fulfillmentRef: "Matthew 21:6-9; John 12:14-15",
    fulfillmentText: "They brought the donkey and the colt... the crowds shouted, 'Hosanna to the Son of David! Blessed is He who comes in the name of the Lord!'",
    written: "c. 520 BC",
    insight: "A conquering king who rides not a war-horse but a borrowed donkey. The whole Gospel is in that humble choice of mount.",
  },
  {
    id: "betrayed",
    theme: "passion",
    prophecyRef: "Psalm 41:9",
    prophecyText: "Even my close friend, someone I trusted, one who shared my bread, has turned against me.",
    fulfillmentRef: "John 13:18, 26",
    fulfillmentText: "'This is to fulfill the Scripture: He who shared my bread has turned against me.' ...He gave the bread to Judas.",
    written: "c. 1000 BC",
    insight: "He knew the kiss was coming, and still dipped the bread and handed it to the one who would sell Him. Love that serves its own betrayer.",
  },
  {
    id: "silver",
    theme: "passion",
    prophecyRef: "Zechariah 11:12-13",
    prophecyText: "They paid me thirty pieces of silver. And the Lord said to me, 'Throw it to the potter' — and I threw it into the house of the Lord to the potter.",
    fulfillmentRef: "Matthew 26:15; 27:3-10",
    fulfillmentText: "They counted out thirty pieces of silver... Judas threw the money into the temple. The priests used it to buy the potter's field.",
    written: "c. 520 BC",
    insight: "The exact price, the exact destination — thrown to a potter, in the house of the Lord. Five hundred years early, down to the coin.",
  },
  {
    id: "silent",
    theme: "passion",
    prophecyRef: "Isaiah 53:7",
    prophecyText: "He was oppressed and afflicted, yet He did not open His mouth; He was led like a lamb to the slaughter, and as a sheep before her shearers is silent.",
    fulfillmentRef: "Matthew 27:12-14",
    fulfillmentText: "When He was accused by the chief priests and the elders, He gave no answer... and the governor was greatly amazed.",
    written: "c. 700 BC",
    insight: "He who spoke the worlds into being held His tongue before His accusers. The silence of the Lamb is louder than any defense.",
  },
  {
    id: "smitten",
    theme: "passion",
    prophecyRef: "Isaiah 50:6",
    prophecyText: "I offered my back to those who beat me, my cheeks to those who pulled out my beard; I did not hide my face from mocking and spitting.",
    fulfillmentRef: "Matthew 26:67; 27:26",
    fulfillmentText: "Then they spit in His face and struck Him with their fists... He had Jesus flogged.",
    written: "c. 700 BC",
    insight: "Every blow was foreseen and freely received. He did not hide His face — He gave it, that we might one day see God face to face.",
  },
  {
    id: "pierced",
    theme: "passion",
    prophecyRef: "Psalm 22:16",
    prophecyText: "Dogs surround me, a band of evil men encircles me; they have pierced my hands and my feet.",
    fulfillmentRef: "John 20:25-27; Luke 23:33",
    fulfillmentText: "'Unless I see the nail marks in His hands...' When they came to the place called the Skull, there they crucified Him.",
    written: "c. 1000 BC",
    insight: "Crucifixion was unknown to Israel when this was written — yet here are the pierced hands and feet, a thousand years before the Roman cross was raised.",
  },
  {
    id: "lots",
    theme: "passion",
    prophecyRef: "Psalm 22:18",
    prophecyText: "They divide my clothes among them and cast lots for my garment.",
    fulfillmentRef: "John 19:23-24",
    fulfillmentText: "'Let's not tear it,' they said. 'Let's decide by lot who will get it.' This happened that the Scripture might be fulfilled.",
    written: "c. 1000 BC",
    insight: "Soldiers gambling at the foot of the Cross, unaware they were acting out an ancient psalm. Even careless hands fulfill the Word.",
  },
  {
    id: "transgressors",
    theme: "passion",
    prophecyRef: "Isaiah 53:12",
    prophecyText: "He poured out His life unto death, and was numbered with the transgressors; for He bore the sin of many, and made intercession for the transgressors.",
    fulfillmentRef: "Mark 15:27-28; Luke 23:34",
    fulfillmentText: "They crucified two rebels with Him, one on His right and one on His left. Jesus said, 'Father, forgive them.'",
    written: "c. 700 BC",
    insight: "Counted among criminals, He prayed for the very men driving the nails. Intercession for transgressors — exactly as foretold.",
  },
  {
    id: "nobones",
    theme: "passion",
    prophecyRef: "Psalm 34:20; Exodus 12:46",
    prophecyText: "He protects all his bones, not one of them will be broken. (Of the Passover lamb: you shall not break any of its bones.)",
    fulfillmentRef: "John 19:33-36",
    fulfillmentText: "When they came to Jesus and found He was already dead, they did not break His legs... these things happened so the Scripture would be fulfilled.",
    written: "c. 1400-1000 BC",
    insight: "The soldiers broke the legs of the others, but not His. The true Passover Lamb, unbroken — slain so that death would pass over us.",
  },
  {
    id: "side",
    theme: "passion",
    prophecyRef: "Zechariah 12:10",
    prophecyText: "They will look on Me, the One they have pierced, and they will mourn for Him as one mourns for an only child.",
    fulfillmentRef: "John 19:34, 37",
    fulfillmentText: "One of the soldiers pierced Jesus' side with a spear, bringing a sudden flow of blood and water. As another Scripture says: 'They will look on the One they have pierced.'",
    written: "c. 520 BC",
    insight: "From His opened side flowed blood and water — the price and the cleansing. God says 'Me' and 'Him' in one breath: pierced, yet still the Lord.",
  },
  {
    id: "buried",
    theme: "passion",
    prophecyRef: "Isaiah 53:9",
    prophecyText: "He was assigned a grave with the wicked, and with the rich in his death, though He had done no violence, nor was any deceit in His mouth.",
    fulfillmentRef: "Matthew 27:57-60",
    fulfillmentText: "A rich man from Arimathea named Joseph... placed it in his own new tomb that he had cut out of the rock.",
    written: "c. 700 BC",
    insight: "Condemned as a criminal, yet buried in a rich man's tomb. The innocent One given an honored grave — the turning of shame toward glory had already begun.",
  },
  {
    id: "resurrection",
    theme: "resurrection",
    prophecyRef: "Psalm 16:10",
    prophecyText: "You will not abandon me to the realm of the dead, nor will you let your faithful one see decay.",
    fulfillmentRef: "Acts 2:31; Matthew 28:5-6",
    fulfillmentText: "David spoke of the resurrection of the Messiah: He was not abandoned to the realm of the dead. 'He is not here; He has risen, just as He said.'",
    written: "c. 1000 BC",
    insight: "The grave could not hold Him, and the prophecy could not be silenced. The empty tomb is the hinge on which all of history turns.",
  },
  {
    id: "ascension",
    theme: "kingship",
    prophecyRef: "Psalm 68:18; Daniel 7:13-14",
    prophecyText: "When You ascended on high, You led captives in Your train. One like a Son of Man came with the clouds; He was given authority, glory and sovereign power; His dominion is an everlasting dominion.",
    fulfillmentRef: "Acts 1:9; Revelation 11:15",
    fulfillmentText: "He was taken up before their very eyes, and a cloud hid Him from their sight. 'The kingdom of the world has become the kingdom of our Lord and of His Christ, and He will reign for ever and ever.'",
    written: "c. 1000-530 BC",
    insight: "He descended into death and rose into reign. King of Kings and Lord of Lords — Rex Regum et Dominus Dominantium — whose dominion has no end.",
  },
];

export const PROPHECY_THEMES = [
  { id: "lineage", label: "Lineage", glyph: "☘" },
  { id: "birth", label: "Birth", glyph: "✶" },
  { id: "ministry", label: "Ministry", glyph: "☉" },
  { id: "passion", label: "Passion", glyph: "✝" },
  { id: "resurrection", label: "Resurrection", glyph: "✺" },
  { id: "kingship", label: "Kingship", glyph: "♔" },
];

export function prophecyOfTheDay(date = new Date()): Prophecy {
  const key = `${date.getFullYear()}-${date.getMonth()}-${date.getDate()}`;
  const oracle = new Oracle(`testimony|${key}`);
  return oracle.pick(PROPHECIES);
}

export function prophecyById(id: string): Prophecy | undefined {
  return PROPHECIES.find((p) => p.id === id);
}
